### ISSUE TITLE
Allow edit table headers and columns

### ISSUE THREAD

**Issue by guibranco** [seed-of-apricot/issue-list-readme#12]
**AS A** user
**I WANT TO** be able to configure the table headings and also which columns will be displayed
**SO THAT** I can use any language for the heading titles and also hide a column, for example `body`

**Acceptance criteria**

A configuration that allow us to set the "display" and "text" properties of the headings as following:

**DEFAULT**
```yml

with:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  labels: ''
  state: 'all'
  titleHeading: 'Title'
  statusHeading: 'Status'
  assigneeHeading: 'Assignee'
  bodyHeading: 'Body'
  titleDisplay: true
  statusDisplay: true  
  assigneeDisplay: true
  bodyDisplay: true
```

**USAGE**

```yml

with:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  titleHeading: 'My custom title'
  assigneeDisplay: false
  bodyDisplay: false
```

Result is the follow table:

| My custom title | Status |
| --- | --- |
| [Issue title](/issues/1) | ✳️ |
| [Another issue](/issues/2) | ✳️ |
