### ISSUE TITLE
cannot find README.md 

### ISSUE THREAD

**Issue by yidilozdemir** [seed-of-apricot/issue-list-readme#13]
Currently trying to use this in my branch, and it has trouble finding the README.md file, which is located in my base directory. 
my yaml file:

```
name: "calendar-view"

on:
    push:
    issues:
      types: [opened, edited, deleted]
      
    
jobs: 
    issue-list:
        runs-on: ubuntu-latest
        steps:
          - name: Dump GitHub context
            env:
              GITHUB_CONTEXT: ${{ toJson(github) }}
            run: echo "$GITHUB_CONTEXT"
          - name: update
            uses: seed-of-apricot/issue-list-readme@v1.1.0
            with:
                GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          - name: add-and-commit
            uses: EndBug/add-and-commit@v4
            with:
                  message: README.md has been re-written
            env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          - name: push
            uses: ad-m/github-push-action@master
            with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                branch: ${{ github.head_ref }}

```

in github actions, the error I am getting:

```
Run seed-of-apricot/issue-list-readme@v1.1.0
Initializing.
GitHub client has been initialized.
Error: ENOENT: no such file or directory, open './README.md'
```

I played around with displaying the branch information etc (as you can see in Dump GitHub context) and trying to set the base directory with uses: working_directory:, both unhelpful. I am doublechecking again to confirm the README file has an .md end. Any ideas?
