### ISSUE TITLE
Issue identifier is not optional

### ISSUE THREAD

**Issue by k0rval4n** [seed-of-apricot/issue-list-readme#14]
### Error:
![image](https://github.com/seed-of-apricot/issue-list-readme/assets/141952843/72aa308a-3b08-4440-9c67-92144de10c4c)

## Action code:
```
name: Test

on:
  issues:
    types: [opened, closed, reopened, deleted]

jobs:
  issue-list:
    runs-on: ubuntu-latest

    permissions:
          contents: write
          pull-requests: write

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: rewriteReadme
        uses: seed-of-apricot/issue-list-readme@v1.1.0
        with:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          pattern: '<!-- issuesTable -->'
          labels: 'good first issue'
          state: 'all'
  
      - name: add-and-commit
        uses: EndBug/add-and-commit@v4
        with:
          message: README.md has been re-written by Github Actions.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
      - name: push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
```

## Partial solution:
Add the identifier to each issue.
![image](https://github.com/seed-of-apricot/issue-list-readme/assets/141952843/632218ec-c8e0-4f1d-a2b0-9b1433083247)
