### ISSUE TITLE
README.md not updated

### ISSUE THREAD

**Issue by apgapg** [seed-of-apricot/issue-list-readme#5]
Hi i tried the steps and the job also worked correctly in workflow logs but i dont see my README updated.
 I only gave access to repo option in secret generation. Is some more permission needs to be given?

https://github.com/apgapg/pie_chart/runs/572801733

**Comment by seed-of-apricot** [comment]
Hi @apgapg, I guess you need to `commit` and `push` the re-written file back into the master branch.  
I use [`EndBug/add-and-commit`](https://github.com/EndBug/add-and-commit) and [`ad-m/github-push-action`](https://github.com/ad-m/github-push-action).

```yml
      - name: add-and-commit
        uses: EndBug/add-and-commit@v4
        with:
          message: README.md has been re-written
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
```
