### ISSUE TITLE
Remove unused `state` variable

### ISSUE THREAD

**Issue by IronicallySerious** [seed-of-apricot/issue-list-readme#6]
Using `state` errors here: https://github.com/sdslabs/ideas/runs/1045748738?check_suite_focus=true

**Comment by seed-of-apricot** [comment]
I can't see the url. Is it possibly a private repo?

**Comment by IronicallySerious** [comment]
Sorry, yes it is a provate repo. I have the logs though and the workflow we used.

toc.yml:
```
name: ToC

on: [issues, push]

jobs:
  rewrite_readme:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: rewriteReadme
        uses: seed-of-apricot/issue-list-readme@v1.0.0
        with:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          labels: 'visible'
          state: 'open'  
      - name: add-and-commit
        uses: EndBug/add-and-commit@v4
        with:
          message: Updated README.md with newly submitted issue
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
```
Logs from the run:

[logs_20.zip](https://github.com/seed-of-apricot/issue-list-readme/files/5147521/logs_20.zip)
